version: "3.8"

services:
  # Mongoose Services
  mongodb:
    container_name: tour-poject_container
    image: mongo:latest
    restart: always
    ports: 
      - 27017:27017
    volumes: 
      - data:/data/db

  
  # Node js API service 
  api: 
    build: .
    ports:
      - 7000:3000
    environment:
      # DB: mongodb://mongodb:27017/tour
      DB_NAME: tour
      NAME: TrulyMittal
    # depends_on: 
    #   - mongodb
    volumes: 
      - .:/tour
    links:
      - mongodb

volumes: 
  data: